### ISSUE TITLE
The source code

### ISSUE THREAD

**Issue by phatberstromgg** [BondDeep/Traffic-Surveillance-System#1]
Hi @BondDeep, your project is great but where is your source code so that I can run it on myself.

Thank you.

**Comment by BondDeep** [comment]
Thank you for your attention to our work. The pseudocode of the system is shown in the paper 'A Traffic Surveillance System for Obtaining Comprehensive Information of the Passing Vehicles Based on Instance Segmentation, IEEE TRANSACTIONS ON INTELLIGENT TRANSPORTATION SYSTEMS (https://ieeexplore.ieee.org/document/9138761)'.

**Comment by BondDeep** [comment]
> 
> 
> Hi @BondDeep, your project is great but where is your source code so that I can run it on myself.
> 
> Thank you.

Thank you for your attention to our work. The pseudocode of the system is shown in the paper 'A Traffic Surveillance System for Obtaining Comprehensive Information of the Passing Vehicles Based on Instance Segmentation, IEEE TRANSACTIONS ON INTELLIGENT TRANSPORTATION SYSTEMS (https://ieeexplore.ieee.org/document/9138761)'.
